/**
 * Monte Carlo Trading Simulator — Built-in Presets
 */

import type { MonteCarloConfig } from "./monte-carlo";

export interface MonteCarloPreset {
  id: string;
  name: string;
  description: string;
  config: MonteCarloConfig;
}

export const BUILT_IN_PRESETS: MonteCarloPreset[] = [
  {
    id: "conservative-swing",
    name: "Conservative Swing",
    description: "Low-risk swing trading with wide stops and small position sizes.",
    config: {
      startingBalance: 10000,
      riskPerTradePercent: 0.5,
      tradeCount: 100,
      simulationCount: 5000,
      winRatePercent: 40,
      averageWinR: 3,
      averageLossR: 1.5,
      positionSizingMode: "fixed",
      includeFees: true,
      feePerTradePercent: 0.1,
      includeSlippage: true,
      slippagePerTradePercent: 0.1,
      outcomeModel: "binary",
      breakEvenRatePercent: 10,
      stopSimulationAtZero: true,
      reduceRiskAfterDrawdown: true,
      reducedRiskTriggerDrawdownPercent: 25,
      reducedRiskPerTradePercent: 0.25,
    },
  },
  {
    id: "trend-follower",
    name: "Trend Follower",
    description: "Classic trend-following: low win rate but large winners, wide R.",
    config: {
      startingBalance: 10000,
      riskPerTradePercent: 1,
      tradeCount: 200,
      simulationCount: 5000,
      winRatePercent: 35,
      averageWinR: 5,
      averageLossR: 1,
      positionSizingMode: "compounding",
      includeFees: true,
      feePerTradePercent: 0.1,
      includeSlippage: true,
      slippagePerTradePercent: 0.15,
      outcomeModel: "distributed",
      winRMin: 2,
      winRMax: 10,
      lossRMin: 0.5,
      lossRMax: 2,
      breakEvenRatePercent: 5,
      stopSimulationAtZero: true,
      reduceRiskAfterDrawdown: true,
      reducedRiskTriggerDrawdownPercent: 20,
      reducedRiskPerTradePercent: 0.5,
    },
  },
  {
    id: "mean-reversion",
    name: "Mean Reversion",
    description: "High win rate, small but frequent gains. Reversal trades.",
    config: {
      startingBalance: 10000,
      riskPerTradePercent: 1,
      tradeCount: 150,
      simulationCount: 5000,
      winRatePercent: 65,
      averageWinR: 1,
      averageLossR: 1.5,
      positionSizingMode: "fixed",
      includeFees: true,
      feePerTradePercent: 0.1,
      includeSlippage: true,
      slippagePerTradePercent: 0.1,
      outcomeModel: "binary",
      breakEvenRatePercent: 0,
      stopSimulationAtZero: true,
      reduceRiskAfterDrawdown: false,
      reducedRiskTriggerDrawdownPercent: 20,
      reducedRiskPerTradePercent: 0.5,
    },
  },
  {
    id: "aggressive-high-risk",
    name: "Aggressive High-Risk",
    description: "Large position sizes. High reward potential but ruin risk is real.",
    config: {
      startingBalance: 10000,
      riskPerTradePercent: 5,
      tradeCount: 100,
      simulationCount: 5000,
      winRatePercent: 50,
      averageWinR: 2,
      averageLossR: 2,
      positionSizingMode: "compounding",
      includeFees: false,
      feePerTradePercent: 0,
      includeSlippage: false,
      slippagePerTradePercent: 0,
      outcomeModel: "binary",
      breakEvenRatePercent: 0,
      stopSimulationAtZero: true,
      reduceRiskAfterDrawdown: false,
      reducedRiskTriggerDrawdownPercent: 20,
      reducedRiskPerTradePercent: 1,
    },
  },
  {
    id: "breakout-trader",
    name: "Breakout Trader",
    description: "Short holding periods, tight stops. Models intraday breakout style.",
    config: {
      startingBalance: 10000,
      riskPerTradePercent: 1,
      tradeCount: 300,
      simulationCount: 5000,
      winRatePercent: 30,
      averageWinR: 3,
      averageLossR: 1,
      positionSizingMode: "compounding",
      includeFees: true,
      feePerTradePercent: 0.2,
      includeSlippage: true,
      slippagePerTradePercent: 0.2,
      outcomeModel: "distributed",
      winRMin: 1.5,
      winRMax: 6,
      lossRMin: 0.5,
      lossRMax: 2,
      breakEvenRatePercent: 10,
      stopSimulationAtZero: true,
      reduceRiskAfterDrawdown: true,
      reducedRiskTriggerDrawdownPercent: 15,
      reducedRiskPerTradePercent: 0.5,
    },
  },
];
